{% set name = "xwebrtc" %}
{% set version = "0.4.1" %}
{% set sha256 = "456a6a4afca412a6dbe2c9885356b2279315620ff45922261e6bfff1e3907d0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwebrtc/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xeus >=0.18.1,<0.19
    - xtl >=0.5.0,<0.6
    - xproperty >=0.8.0,<0.9
    - xwidgets >=0.16.0,<0.17

test:
  commands:
    - test -d ${PREFIX}/include/xwebrtc  # [unix]
    - test -f ${PREFIX}/include/xwebrtc/xchat.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwebrtc\xchat.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the jupyter webrtc widget'
  dev_url: https://github.com/QuantStack/xwebrtc

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
